# Generated by Django 6.0 on 2026-01-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_periodcycle_cycle_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Anxious', 'Anxious'), ('Tired', 'Tired'), ('Irritable', 'Irritable')], max_length=20)),
                ('cramps', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=5)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='core.periodcycle')),
            ],
        ),
    ]
